<div class="emoticon" onclick="appendToMessage(':smile:')">:smile:</div>
<div class="emoticon" onclick="appendToMessage(':laughing:')">:laughing:</div>
<div class="emoticon" onclick="appendToMessage(':joy:')">:joy:</div>
<div class="emoticon" onclick="appendToMessage(':sweat_smile:')">:sweat_smile:</div>
<div class="emoticon" onclick="appendToMessage(':innocent:')">:innocent:</div>
<div class="emoticon" onclick="appendToMessage(':wink:')">:wink:</div>
<div class="emoticon" onclick="appendToMessage(':blush:')">:blush:</div>
<div class="emoticon" onclick="appendToMessage(':slight_smile:')">:slight_smile:</div>
<div class="emoticon" onclick="appendToMessage(':yum:')">:yum:</div>
<div class="emoticon" onclick="appendToMessage(':heart_eyes:')">:heart_eyes:</div>
<div class="emoticon" onclick="appendToMessage(':kissing_heart:')">:kissing_heart:</div>
<div class="emoticon" onclick="appendToMessage(':stuck_out_tongue_winking_eye:')">:stuck_out_tongue_winking_eye:</div>
<div class="emoticon" onclick="appendToMessage(':stuck_out_tongue_closed_eyes:')">:stuck_out_tongue_closed_eyes:</div>
<div class="emoticon" onclick="appendToMessage(':stuck_out_tongue:')">:stuck_out_tongue:</div>
<div class="emoticon" onclick="appendToMessage(':nerd:')">:nerd:</div>
<div class="emoticon" onclick="appendToMessage(':money_mouth:')">:money_mouth:</div>
<div class="emoticon" onclick="appendToMessage(':sunglasses:')">:sunglasses:</div>
<div class="emoticon" onclick="appendToMessage(':hugging:')">:hugging:</div>
<div class="emoticon" onclick="appendToMessage(':smirk:')">:smirk:</div>
<div class="emoticon" onclick="appendToMessage(':no_mouth:')">:no_mouth:</div>
<div class="emoticon" onclick="appendToMessage(':neutral_face:')">:neutral_face:</div>
<div class="emoticon" onclick="appendToMessage(':expressionless:')">:expressionless:</div>
<div class="emoticon" onclick="appendToMessage(':rolling_eyes:')">:rolling_eyes:</div>
<div class="emoticon" onclick="appendToMessage(':thinking:')">:thinking:</div>
<div class="emoticon" onclick="appendToMessage(':flushed:')">:flushed:</div>
<div class="emoticon" onclick="appendToMessage(':unamused:')">:unamused:</div>
<div class="emoticon" onclick="appendToMessage(':disappointed:')">:disappointed:</div>
<div class="emoticon" onclick="appendToMessage(':worried:')">:worried:</div>
<div class="emoticon" onclick="appendToMessage(':angry:')">:angry:</div>
<div class="emoticon" onclick="appendToMessage(':rage:')">:rage:</div>
<div class="emoticon" onclick="appendToMessage(':pensive:')">:pensive:</div>
<div class="emoticon" onclick="appendToMessage(':confused:')">:confused:</div>
<div class="emoticon" onclick="appendToMessage(':slight_frown:')">:slight_frown:</div>
<div class="emoticon" onclick="appendToMessage(':frowning2:')">:frowning2:</div>
<div class="emoticon" onclick="appendToMessage(':persevere:')">:persevere:</div>
<div class="emoticon" onclick="appendToMessage(':confounded:')">:confounded:</div>
<div class="emoticon" onclick="appendToMessage(':tired_face:')">:tired_face:</div>
<div class="emoticon" onclick="appendToMessage(':weary:')">:weary:</div>
<div class="emoticon" onclick="appendToMessage(':triumph:')">:triumph:</div>
<div class="emoticon" onclick="appendToMessage(':open_mouth:')">:open_mouth:</div>
<div class="emoticon" onclick="appendToMessage(':scream:')">:scream:</div>
<div class="emoticon" onclick="appendToMessage(':fearful:')">:fearful:</div>
<div class="emoticon" onclick="appendToMessage(':cold_sweat:')">:cold_sweat:</div>
<div class="emoticon" onclick="appendToMessage(':hushed:')">:hushed:</div>
<div class="emoticon" onclick="appendToMessage(':frowning:')">:frowning:</div>
<div class="emoticon" onclick="appendToMessage(':anguished:')">:anguished:</div>
<div class="emoticon" onclick="appendToMessage(':cry:')">:cry:</div>
<div class="emoticon" onclick="appendToMessage(':disappointed_relieved:')">:disappointed_relieved:</div>
<div class="emoticon" onclick="appendToMessage(':sleepy:')">:sleepy:</div>
<div class="emoticon" onclick="appendToMessage(':yum:')">:yum:</div>
<div class="emoticon" onclick="appendToMessage(':sleeping:')">:sleeping:</div>
<div class="emoticon" onclick="appendToMessage(':sob:')">:sob:</div>
<div class="emoticon" onclick="appendToMessage(':dizzy_face:')">:dizzy_face:</div>
<div class="emoticon" onclick="appendToMessage(':astonished:')">:astonished:</div>
<div class="emoticon" onclick="appendToMessage(':zipper_mouth:')">:zipper_mouth:</div>
<div class="emoticon" onclick="appendToMessage(':mask:')">:mask:</div>
<div class="emoticon" onclick="appendToMessage(':thermometer_face:')">:thermometer_face:</div>
<div class="emoticon" onclick="appendToMessage(':head_bandage:')">:head_bandage:</div>
<div class="emoticon" onclick="appendToMessage(':hugging:')">:hugging:</div>
<div class="emoticon" onclick="appendToMessage(':zzz:')">:zzz:</div>
<div class="emoticon" onclick="appendToMessage(':poop:')">:poop:</div>
<div class="emoticon" onclick="appendToMessage(':smiling_imp:')">:smiling_imp:</div>
<div class="emoticon" onclick="appendToMessage(':imp:')">:imp:</div>
<div class="emoticon" onclick="appendToMessage(':head_bandage:')">:ghost:</div>
<div class="emoticon" onclick="appendToMessage(':smiley_cat:')">:smiley_cat:</div>
<div class="emoticon" onclick="appendToMessage(':smile_cat:')">:smile_cat:</div>
<div class="emoticon" onclick="appendToMessage(':joy_cat:')">:joy_cat:</div>
<div class="emoticon" onclick="appendToMessage(':heart_eyes_cat:')">:heart_eyes_cat:</div>
<div class="emoticon" onclick="appendToMessage(':smirk_cat:')">:smirk_cat:</div>
<div class="emoticon" onclick="appendToMessage(':kissing_cat:')">:kissing_cat:</div>
<div class="emoticon" onclick="appendToMessage(':scream_cat:')">:scream_cat:</div>
<div class="emoticon" onclick="appendToMessage(':crying_cat_face:')">:crying_cat_face:</div>
<div class="emoticon" onclick="appendToMessage(':pouting_cat:')">:pouting_cat:</div>
<div class="emoticon" onclick="appendToMessage(':raised_hands:')">:raised_hands:</div>
<div class="emoticon" onclick="appendToMessage(':clap:')">:clap:</div>
<div class="emoticon" onclick="appendToMessage(':wave:')">:wave:</div>
<div class="emoticon" onclick="appendToMessage(':punch:')">:punch:</div>
<div class="emoticon" onclick="appendToMessage(':thumbsup:')">:thumbsup:</div>
<div class="emoticon" onclick="appendToMessage(':fist:')">:fist:</div>
<div class="emoticon" onclick="appendToMessage(':v:')">:v:</div>
<div class="emoticon" onclick="appendToMessage(':ok_hand:')">:ok_hand:</div>
<div class="emoticon" onclick="appendToMessage(':raised_hand:')">:raised_hand:</div>
<div class="emoticon" onclick="appendToMessage(':open_hands:')">:open_hands:</div>
<div class="emoticon" onclick="appendToMessage(':muscle:')">:muscle:</div>
<div class="emoticon" onclick="appendToMessage(':pray:')">:pray:</div>
<div class="emoticon" onclick="appendToMessage(':point_up_2:')">:point_up_2:</div>
<div class="emoticon" onclick="appendToMessage(':point_down:')">:point_down:</div>
<div class="emoticon" onclick="appendToMessage(':point_left:')">:point_left:</div>
<div class="emoticon" onclick="appendToMessage(':point_right:')">:point_up_2:</div>
<div class="emoticon" onclick="appendToMessage(':metal:')">:point_down:</div>
<div class="emoticon" onclick="appendToMessage(':lips:')">:lips:</div>
<div class="emoticon" onclick="appendToMessage(':tongue:')">:tongue:</div>
<div class="emoticon" onclick="appendToMessage(':couple_with_heart:')">:couple_with_heart:</div>
<div class="emoticon" onclick="appendToMessage(':couple:')">:couple:</div>